### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by rmmto** [vmoebius/node-fiql-parser#1]
At running on IE 11 an error ocures  the error is in the the file libs\utils.js.
The message error is Syntax error at line 18 const convertFromNode = exports.convertFromNode = node => 
I believe that the problem its related with the way how the code was transpiled.

Congratz

**Comment by vmoebius** [comment]
The `node-fiql-parser` module has been developed for application only in recent versions of node.js so far.
How did you manage to import it in IE11?
Why did you close the issue?

**Comment by rmmto** [comment]
Hi,
I put the issue in the wrong place.
Congratz
